# Generated by Django 3.2.18 on 2023-07-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20230712_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('finalprice', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField(default='This is Sample Product')),
                ('pic1', models.ImageField(upload_to='uploads/product')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/product')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/product')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/product')),
                ('brandproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.brand')),
                ('maincategoryproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.maincategory')),
                ('subcategoryproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory')),
            ],
        ),
    ]
