# Generated by Django 3.2.18 on 2023-07-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='product',
        ),
    ]
