# Generated by Django 3.2.18 on 2023-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
