# Generated by Django 3.2.18 on 2023-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_rename_checkproduct_checkoutproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='selected_address_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_address_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_address_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_address_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_address_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_address_pin',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='checkout',
            name='selected_address_state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
