# Generated by Django 3.2.18 on 2023-07-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20230731_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='selected_address_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='selected_address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='selected_address_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='selected_address_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='selected_address_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='selected_address_pin',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='selected_address_state',
            new_name='state',
        ),
    ]
