# Generated by Django 3.2.18 on 2023-08-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20230801_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsletter',
            new_name='newslatter',
        ),
    ]
