# Generated by Django 3.2.18 on 2023-08-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_rename_newsletter_newslatter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
