# Generated by Django 3.2.18 on 2023-08-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20230802_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userlocation',
        ),
    ]
